### ISSUE TITLE
Incluir totais do PIS e COFINS

### ISSUE THREAD

**Issue by renatonlima** [Engenere/BrazilFiscalReport#19]
No DANFE esta faltando incluir os campos totais do PIS e COFINS como no exemplo abaixo:

![image](https://github.com/Engenere/BrazilFiscalReport/assets/211005/aecca460-718d-4161-aecd-7f20c9233e0a)

Estou registrando esse issue para não esquecer esse detalhe quando o PR https://github.com/OCA/l10n-brazil/pull/3068 for aprovado e para ser implementado futuramente.

**Comment by antoniospneto** [comment]
Olá @renatonlima, obrigado pela observação! Pelo que entendi, esses campos não são obrigatórios, permitindo ao emissor decidir se deseja ou não exibir esses valores na DANFE. Gostaria de saber se essa é uma necessidade real para algum caso específico ou se você estava apenas comparando as diferenças com a DANFE gerada pelo erpbrasil.edoc.pdf.

Se for uma necessidade real, me comprometo a adicionar essa funcionalidade. Posso incluir uma opção no configurador para que o usuário escolha se deseja exibir ou não o total de PIS e COFINS.

**Comment by renatonlima** [comment]
@antoniospneto,

Os totais dos impostos de PIS e COFINS são importante no caso da emissão de NF-e de entrada de importação onde o valor do PIS e COFINS são somados ao valor total da NF-e, nesse caso é importante o DANFE ter esses valores para ao visualiza-lo consiga conferir o total da NF-e, no momento eu me recordo especificamente desse caso, além desse caso, seria interessante também aparecer nos casos de saídas (venda) como informativo.

**Comment by antoniospneto** [comment]
@renatonlima resolvido no #20
logo faço o release com as novas alterações.
valeu!
