### ISSUE TITLE
[DANFE] Cancelado / Rascunho / Denegado

### ISSUE THREAD

**Issue by mileo** [Engenere/BrazilFiscalReport#25]
Caso a nota não esteja autorizada o DANFE precisa ter no status superior seu texto alterado, por exemplo:

![image](https://github.com/user-attachments/assets/ba4e39b1-580d-4d0b-831f-eec3448a6b9e)

**Se não tiver protocolo:**

- Impresso para simples conferência / Informações não transmitidas a nenhuma / SEFAZ autorizadora SEM VALOR FISCAL

**Status 110, 301, 302:**

- A circulação da mercadoria foi PROIBIDA pela SEFAZ autorizadora, devido a irregularidades fiscais;

** Não estiver no status 110, 301, 302 **

-  Consulta de autenticidade no portal nacional da NF-e [www.nfe.fazenda.gov.br](http://www.nfe.fazenda.gov.br/)

Também seria interessante uma marca d'agua como no exemplo:

![image](https://github.com/user-attachments/assets/81f182a2-e115-4099-bf1b-84861f4f4947)

**Comment by mileo** [comment]
![image](https://github.com/user-attachments/assets/0e55c145-e8b9-4f62-8739-1e282bc2c4ac)

@antoniospneto essa marca d'agua ela vem da lib, do Odoo? Só aparece para NFe emitidas em ambiente de homologação?

**Comment by antoniospneto** [comment]
@mileo 

Sim, vem da propria lib da DANFE a marca da agua "sem valor fiscal"
Hoje isso está sendo impresso somente quando o tipo de ambiente está como homologação.
Mas realmente falta aplicar quando não há protocolo de autorização no xml, independente se é ambiente de homologação ou não. Vou atualizar a biblioteca para incluir isso.

Quanto ao status, cancelado e denegado tem certeza quando a isso? eu não vejo mutio sentido em fazer isso, pois não vai existir um xml (tag nfeproc) com o protocolo denegado ou cancelamento...

**Comment by antoniospneto** [comment]
@mileo 

Essa questão do "cancelado" ou "denegado" na DANFE foge do seu proposito oficial, ao fazer isso será apenas para mero controle gerencial certo? ai teria que pensar em como será passado essa informação para a biblioteca.. pois tecnicamente o xml da nota fiscal é imutavel, se formos implementar isso como você sugere?

**Comment by antoniospneto** [comment]
Quanto a NFe sem autorização de uso resolvido na PR #26 

Em relação às notas Denegadas ou Canceladas, é necessário analisar com mais cuidado. Essas informações não estão presentes no XML que representa o documento NF-e, então seria preciso passar essa informação para a biblioteca como um parâmetro opcional. Dessa forma, poderíamos imprimi-las na DANFE. Vale ressaltar que isso seria apenas uma funcionalidade extra de gerenciamento e não faz parte do propósito principal da DANFE, pois o manual não aborda esse tipo de situação. No entanto, se alguém quiser desenvolver e propor essa funcionalidade, podemos considerar incluí-la na biblioteca.
