### ISSUE TITLE
[DANFE] Formato de impressão

### ISSUE THREAD

**Issue by DiegoParadeda** [Engenere/BrazilFiscalReport#28]
O formato padrão de impressão de DANFE está saindo com as margens cortadas:

![image](https://github.com/user-attachments/assets/702963e9-4252-4063-b8b1-e529476699b7)

![image](https://github.com/user-attachments/assets/a0ead197-52a5-4065-91f1-46b2c84fbb5e)

Isso pode ser facilmente ajustado nas configurações de impressão de cada usuário, mas a primeira impressão fica sempre meio cortada.

Será que não seria o caso de aumentar as margens diretamente no documento, pra ficar mais simples de usar?

**Comment by antoniospneto** [comment]
@DiegoParadeda 

De fato, não é interessante mudar a margem diretamente na configuração da impressora, pois isso vai mudar a escala da impressão e a fonte pode ficar pequena, fora do padrão, a biblioteca foi construida de forma que isso realmente não seja necessario.

A propria lib permite a configuração da margem, e lá no projeto da localização do Odoo eu vou propor uma PR para permitir a customização da margem, veja o rascunho aqui: https://github.com/Engenere/l10n-brazil/pull/24

Quanto a tornar a margem padrão maior, acho que pode ser tbm, eu fiz assim pra maximar o espaço, mas concordo que pode dar problema com a maior parte das impressoras, não são todoas que conseguem trabalhar com uma margem bem pequena. Quem desejar menor pode alterar a configuração padrão.

**Comment by DiegoParadeda** [comment]
@antoniospneto entendi! Vou testar com o PR que você comentou então, valeu!

**Comment by antoniospneto** [comment]
Resolvido no #31. publicado a versão 0.4.3 com a correção.
