### ISSUE TITLE
Tipo frete em desacordo com a especificação da NF-e

### ISSUE THREAD

**Issue by mileo** [Engenere/BrazilFiscalReport#32]
![image](https://github.com/user-attachments/assets/72c3ae10-c76b-4752-b0a0-bfe36dec3afa)

```
TRANSP_MODFRETE = [
    ("0", " Contratação do Frete por conta do Remetente (CIF)"),
    ("1", " Contratação do Frete por conta do destinatário/remetente (FOB)"),
    ("2", " Contratação do Frete por conta de terceiros"),
    ("3", " Transporte próprio por conta do remetente"),
    ("4", " Transporte próprio por conta do destinatário"),
    ("9", " Sem Ocorrência de transporte."),
]
```

**Comment by mileo** [comment]
Atualmente definido de forma abreviada / com outras palavras:

https://github.com/Engenere/BrazilFiscalReport/blob/main/brazilfiscalreport/danfe/danfe.py#L32C1-L39C2

**Comment by antoniospneto** [comment]
@mileo, os tipos estão corretos, a diferença é que estamos utilizando os nomes reduzidos, você acha que isso é um problema? Pelo que vejo a maioria das empresas fazem dessa forma, se isso realmente for um problemas vamos precisar fazer quebra de linha nesse campo, pois os nomes são muito grande, ocupando mais espaço na DANFE

**Comment by antoniospneto** [comment]
as modalidades estão de acordo, estou fechando a issue, mais detalhes em: https://github.com/Engenere/BrazilFiscalReport/pull/33#issuecomment-2412010363
