### ISSUE TITLE
Renderização duplicada da unidade do produto uTrib e uCom

### ISSUE THREAD

**Issue by phelipealves** [Engenere/BrazilFiscalReport#46]
## Problema

Atualmente, quando as tags `uTrib` e `uCom` do produto estão preenchidas no arquivo `XML`, realizamos um merge dessas informações e exibimos ambas na coluna `UN.` do produto no PDF gerado.

No entanto, essa abordagem pode causar confusão para quem lê o documento, já que é mais comum apresentar apenas a unidade comercializada, considerando que, na maioria dos casos, as duas informações são idênticas.

### Caso 1: Diferença no formato das unidades

Um cenário específico ocorre quando:

- `uTrib` = `UN`  
- `uCom` = `un`

Ao utilizarmos a função `merge_if_different`, como `UN` ≠ `un`, ambas as informações são combinadas e exibidas. Isso ocorre mesmo sendo, essencialmente, a mesma unidade, com uma diferença apenas no formato do texto.

---

### Caso 2: Diferença após arredondamento de valores

Outro cenário ocorre quando:

- `vUnTrib` = `14.025833`  
- `vUnCom` = `14.025851`

Antes de aplicar a função `merge_if_different`, os valores passam pela função `format_number`, que realiza o arredondamento. Isso pode causar uma diferença artificial entre os valores, resultando na seguinte situação:

- `vUnTrib` = `14.0258`  
- `vUnCom` = `14.0259`

Mesmo com uma diferença mínima, os valores são tratados como distintos e exibidos juntos.

---

<img width="318" alt="Screenshot 2024-12-06 at 12 01 41" src="https://github.com/user-attachments/assets/8999f63c-40c4-4802-b861-460c44c75b8d">

## Proposta de Solução

Após conversas com clientes da área fiscal, foi constatado que exibir ambas as informações é redundante e desnecessário. A solução proposta consiste em:

1. **Caso 1**: Priorizar a exibição da unidade comercializada (`uCom`), eliminando a duplicidade de informações.
   
2. **Caso 2**: Priorizar o valor unitário comercializado (`vUnCom`), evitando exibir valores redundantes.

Além disso, para situações onde o `merge_if_different` for necessário, recomendamos:

- Substituir o arredondamento pelo uso dos valores decimais reais, cortando os dígitos excedentes antes de qualquer transformação, para evitar diferenças artificiais entre os números.

Essa abordagem simplificará a leitura do PDF, garantindo clareza e precisão nas informações exibidas.

**Comment by phelipealves** [comment]
@antoniospneto  @CristianoMafraJunior

**Comment by antoniospneto** [comment]
@phelipealves 

Acho que se a gente modificar um pouco o função `merge_if_different` para que se torne case-insensitive, no caso não diferenciar entre maiúsculas e minúsculas o problema já é resolvido, pois ai "un" será igual "UN". 

Por exemple, daria pra ser feito assim:

```
def merge_if_different(value1, value2):
    str_val1 = str(value1).lower()
    str_val2 = str(value2).lower()
    if str_val1 != str_val2:
        return f"{value1}\n{value2}"
    else:
        return value1
```

ai para que a preferencia seja a **uCom**, na só garantir que o **uCom** seja passado como primeiro parametro, no `value1` quando for usar a função.

**Comment by antoniospneto** [comment]
Quanto ao preço, será que no xml os dois preços estão exatamente iguais? penso que pro arrredondado ter ficado diferente as ultimas casas no xml tbm não devem estar iguais, obs, se quiser aumentar a quantidade de casas decimais exibidas tem essa configuração disponivel.

**Comment by phelipealves** [comment]
Oi @antoniospneto ! Muito obrigado pela resposta ❤️ 

Conversando com outras pessoas por aqui e analisando outros documentos, percebi que não é comum apresentar duas informações nessas colunas. Normalmente, é exibido apenas o valor comercial, e não o tributário. Até porque, na maioria dos casos, essas informações são iguais, e os documentos mostram apenas um valor, não dois.

Por isso, gostaria de entender contigo: qual seria a motivação para exibirmos ambos os dados nesses campos quando eles são diferentes? 😊

**Comment by antoniospneto** [comment]
> Oi @antoniospneto ! Muito obrigado pela resposta ❤️
> 
> Conversando com outras pessoas por aqui e analisando outros documentos, percebi que não é comum apresentar duas informações nessas colunas. Normalmente, é exibido apenas o valor comercial, e não o tributário. Até porque, na maioria dos casos, essas informações são iguais, e os documentos mostram apenas um valor, não dois.
> 
> Por isso, gostaria de entender contigo: qual seria a motivação para exibirmos ambos os dados nesses campos quando eles são diferentes? 😊

@phelipealves 

Na verdade a nossa intenção é só exibir as duas informações apenas no caso que comercial difere do tributavel, nos casos que é o mesmo não é pra repetir na impressão. O proprio manual da DANFE deixa claro essa parte, veja:
![image](https://github.com/user-attachments/assets/2df0a9cb-41c6-4c6e-8b62-570586b459e9)
Pagina 11, link: https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=f%20NhsSn3/5M=

Hoje eu tbm não tenho casos de uso de clientes que utilizam essa funcionalidade, mas já experimentei outras ferramentas de geração de DANFE que faz da mesma forma.

**Comment by antoniospneto** [comment]
@phelipealves

Como referencia, podemos ver o projeto opensource ACBR, que tbm faz dessa forma:

https://www.projetoacbr.com.br/forum/topic/67336-nfe-danfe-com-as-tags-ceantrib-utrib-qtrib-e-vuntrib/

**Comment by phelipealves** [comment]
@antoniospneto.

faz sentido mesmo atuar apenas no caso 1 e deixar o caso 2 apenas com a lógica que exist e hoje com a aproximação dos valores pelas casas decimais.

Obrigado de + pela documentação de exibição do arquivo, vou ler para os outros campos também 🚀
